include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

# Exclude Freezed files from static analysis
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"