name: weather
description: Dart package to manage weather data and domain layers.
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Scoped Packages
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  dartz: ^0.10.0-nullsafety.1
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  mocktail: ^0.1.0
  test: ^1.16.8
  very_good_analysis: ^2.0.0
